### ISSUE TITLE
Jailstick

### ISSUE THREAD

**Issue by Curtis73** [graywolf336/Jail#120]
Hi, I have an issue with the Jail sticks. I am running the latest version of jail for 1.8.8. In the configs, I set it up as showed in the wiki, but the jail when they are on low health doesn't work. (The jail on low health feature - everything else works) Here is what I have in the configs: 
```
jailstick:
  enabled: true
  sticks:
  - stick,5m,deatheater,Death Eater,10
```
am I right in thinking that after the second "Death Eater" it is the health?
and is there a way to put them into a specific cell with the stick?
Thanks!
